//
//  SampleData.swift
//  TTS Voca
//
//  Created by 정지환 on 11/06/2019.
//  Copyright © 2019 Jihwan Jung. All rights reserved.
//

import Foundation

class SampleData {
    
    init() {

    }
    
    func getSampleVoca() -> [Voca] {
        let date: Date = Date()
        var sampleVoca: [Voca] = [Voca]()
        
        switch Locale.current.languageCode {
        case "ko":
            // English (United States)
            let sampleVoca1: Voca = Voca()
            sampleVoca1.setTitle(title: "영어 단어장")
            sampleVoca1.setNum(num: -5)
            sampleVoca1.setCreateDate(uploadDate: date)
            sampleVoca1.setLanguage(language: "English (United States)")
            sampleVoca1.setE_Status(e_Status: 0)
            sampleVoca1.setE_Date(e_Date: date)
            sampleVoca1.setTag(tag: 1)
            sampleVoca1.setLearningCount(learningCount: 0)
            sampleVoca1.setLearningTime(learningTime: 0)
            sampleVoca1.setWordCount(wordCount: 12)
            sampleVoca1.setWordList(words: ["culture", "experience", "education", "symbol", "master", "liberty", "tradition", "source", "revolution", "candle", "population", "pet"])
            sampleVoca1.setMeanList(means: ["문화", "경험", "교육", "상징", "주인", "자유", "전통", "출처", "혁명", "양초", "인구", "애완동물"])
            sampleVoca.append(sampleVoca1)
            
            // Japanese (Japan)
            let sampleVoca2: Voca = Voca()
            sampleVoca2.setTitle(title: "일본어 단어장")
            sampleVoca2.setNum(num: -4)
            sampleVoca2.setCreateDate(uploadDate: date)
            sampleVoca2.setLanguage(language: "Japanese (Japan)")
            sampleVoca2.setE_Status(e_Status: 0)
            sampleVoca2.setE_Date(e_Date: date)
            sampleVoca2.setTag(tag: 2)
            sampleVoca2.setLearningCount(learningCount: 0)
            sampleVoca2.setLearningTime(learningTime: 0)
            sampleVoca2.setWordCount(wordCount: 12)
            sampleVoca2.setWordList(words: ["文化", "経験", "教育", "象徴", "主人", "自由", "伝統", "ソース", "革命", "キャンドル", "人口", "ペット"])
            sampleVoca2.setMeanList(means: ["문화", "경험", "교육", "상징", "주인", "자유", "전통", "출처", "혁명", "양초", "인구", "애완동물"])
            sampleVoca.append(sampleVoca2)
            
            // Hindi (India)
            let sampleVoca3: Voca = Voca()
            sampleVoca3.setTitle(title: "힌디어 단어장")
            sampleVoca3.setNum(num: -3)
            sampleVoca3.setCreateDate(uploadDate: date)
            sampleVoca3.setLanguage(language: "Hindi (India)")
            sampleVoca3.setE_Status(e_Status: 0)
            sampleVoca3.setE_Date(e_Date: date)
            sampleVoca3.setTag(tag: 3)
            sampleVoca3.setLearningCount(learningCount: 0)
            sampleVoca3.setLearningTime(learningTime: 0)
            sampleVoca3.setWordCount(wordCount: 12)
            sampleVoca3.setWordList(words: ["संस्कृति", "अनुभव", "शिक्षा", "मार्क", "मेज़बान", "स्वतंत्रता", "परंपरा", "स्रोत", "क्रांति", "मोमबत्ती", "आबादी", "पालतू जानवर"])
            sampleVoca3.setMeanList(means: ["문화", "경험", "교육", "마크", "주인", "독립", "전통", "출처", "혁명", "양초", "인구", "애완동물"])
            sampleVoca.append(sampleVoca3)
            
            
            // Chinese (China)
            let sampleVoca4: Voca = Voca()
            sampleVoca4.setTitle(title: "중국어 단어장")
            sampleVoca4.setNum(num: -2)
            sampleVoca4.setCreateDate(uploadDate: date)
            sampleVoca4.setLanguage(language: "Chinese (China)")
            sampleVoca4.setE_Status(e_Status: 0)
            sampleVoca4.setE_Date(e_Date: date)
            sampleVoca4.setTag(tag: 4)
            sampleVoca4.setLearningCount(learningCount: 0)
            sampleVoca4.setLearningTime(learningTime: 0)
            sampleVoca4.setWordCount(wordCount: 12)
            sampleVoca4.setWordList(words: ["文化", "经验", "教育", "标记", "主", "自由", "传统", "源", "革命", "蜡烛", "人口", "宠物"])
            sampleVoca4.setMeanList(means: ["문화", "경험", "교육", "마크", "주인", "자유", "전통", "출처", "혁명", "양초", "인구", "애완동물"])
            sampleVoca.append(sampleVoca4)
            
            
            // Spanish (Spain)
            let sampleVoca5: Voca = Voca()
            sampleVoca5.setTitle(title: "스페인어 단어장")
            sampleVoca5.setNum(num: -1)
            sampleVoca5.setCreateDate(uploadDate: date)
            sampleVoca5.setLanguage(language: "Spanish (Spain)")
            sampleVoca5.setE_Status(e_Status: 0)
            sampleVoca5.setE_Date(e_Date: date)
            sampleVoca5.setTag(tag: 5)
            sampleVoca5.setLearningCount(learningCount: 0)
            sampleVoca5.setLearningTime(learningTime: 0)
            sampleVoca5.setWordCount(wordCount: 12)
            sampleVoca5.setWordList(words: ["La cultura", "Experiencia", "Educacion", "Símbolo", "Maestro", "La libertad", "La tradicion", "Fuente", "Revolución", "Las velas", "Poblacion", "Las mascotas"])
            sampleVoca5.setMeanList(means: ["문화", "경험", "교육", "상징", "주인", "자유", "전통", "출처", "혁명", "양초", "인구", "애완동물"])
            sampleVoca.append(sampleVoca5)
            
            // 이하는 삭제
//            let sampleVoca6: Voca = Voca()
//            sampleVoca6.setTitle(title: "test")
//            sampleVoca6.setNum(num: -6)
//            sampleVoca6.setCreateDate(uploadDate: date)
//            sampleVoca6.setLanguage(language: "English (United States)")
//            sampleVoca6.setE_Status(e_Status: 6)
//            sampleVoca6.setE_Date(e_Date: date)
//            sampleVoca6.setTag(tag: 1)
//            sampleVoca6.setLearningCount(learningCount: 0)
//            sampleVoca6.setLearningTime(learningTime: 0)
//            sampleVoca6.setWordCount(wordCount: 4)
//            sampleVoca6.setWordList(words: ["1", "2", "3", "4"])
//            sampleVoca6.setMeanList(means: ["1", "2", "3", "4"])
//            sampleVoca.append(sampleVoca6)
            break
        case "ja":
            // English (United States)
            let sampleVoca1: Voca = Voca()
            sampleVoca1.setTitle(title: "英語単語帳")
            sampleVoca1.setNum(num: -5)
            sampleVoca1.setCreateDate(uploadDate: date)
            sampleVoca1.setLanguage(language: "English (United States)")
            sampleVoca1.setE_Status(e_Status: 0)
            sampleVoca1.setE_Date(e_Date: date)
            sampleVoca1.setTag(tag: 1)
            sampleVoca1.setLearningCount(learningCount: 0)
            sampleVoca1.setLearningTime(learningTime: 0)
            sampleVoca1.setWordCount(wordCount: 12)
            sampleVoca1.setWordList(words: ["culture", "experience", "education", "symbol", "master", "liberty", "tradition", "source", "revolution", "candle", "population", "pet"])
            sampleVoca1.setMeanList(means: ["文化", "経験", "教育", "象徴", "主人", "自由", "伝統", "ソース", "革命", "キャンドル", "人口", "ペット"])
            sampleVoca.append(sampleVoca1)
            
            // Korean (South Korea)
            let sampleVoca2: Voca = Voca()
            sampleVoca2.setTitle(title: "韓国語単語帳")
            sampleVoca2.setNum(num: -4)
            sampleVoca2.setCreateDate(uploadDate: date)
            sampleVoca2.setLanguage(language: "Korean (South Korea)")
            sampleVoca2.setE_Status(e_Status: 0)
            sampleVoca2.setE_Date(e_Date: date)
            sampleVoca2.setTag(tag: 2)
            sampleVoca2.setLearningCount(learningCount: 0)
            sampleVoca2.setLearningTime(learningTime: 0)
            sampleVoca2.setWordCount(wordCount: 12)
            sampleVoca2.setWordList(words: ["문화", "경험", "교육", "상징", "주인", "자유", "전통", "출처", "혁명", "양초", "인구", "애완동물"])
            sampleVoca2.setMeanList(means: ["文化", "経験", "教育", "象徴", "主人", "自由", "伝統", "ソース", "革命", "キャンドル", "人口", "ペット"])
            sampleVoca.append(sampleVoca2)
            
            // Hindi (India)
            let sampleVoca3: Voca = Voca()
            sampleVoca3.setTitle(title: "ヒンディー語単語帳") // ヒンディー語の語彙
            sampleVoca3.setNum(num: -3)
            sampleVoca3.setCreateDate(uploadDate: date)
            sampleVoca3.setLanguage(language: "Hindi (India)")
            sampleVoca3.setE_Status(e_Status: 0)
            sampleVoca3.setE_Date(e_Date: date)
            sampleVoca3.setTag(tag: 3)
            sampleVoca3.setLearningCount(learningCount: 0)
            sampleVoca3.setLearningTime(learningTime: 0)
            sampleVoca3.setWordCount(wordCount: 12)
            sampleVoca3.setWordList(words: ["संस्कृति", "अनुभव", "शिक्षा", "मार्क", "मेज़बान", "स्वतंत्रता", "परंपरा", "स्रोत", "क्रांति", "मोमबत्ती", "आबादी", "पालतू जानवर"])
            sampleVoca3.setMeanList(means: ["文化", "経験", "教育", "象徴", "主人", "自由", "伝統", "ソース", "革命", "キャンドル", "人口", "ペット"])
            sampleVoca.append(sampleVoca3)
            
            
            // Chinese (China)
            let sampleVoca4: Voca = Voca()
            sampleVoca4.setTitle(title: "中国語単語帳") // 中国語の語彙
            sampleVoca4.setNum(num: -2)
            sampleVoca4.setCreateDate(uploadDate: date)
            sampleVoca4.setLanguage(language: "Chinese (China)")
            sampleVoca4.setE_Status(e_Status: 0)
            sampleVoca4.setE_Date(e_Date: date)
            sampleVoca4.setTag(tag: 4)
            sampleVoca4.setLearningCount(learningCount: 0)
            sampleVoca4.setLearningTime(learningTime: 0)
            sampleVoca4.setWordCount(wordCount: 12)
            sampleVoca4.setWordList(words: ["文化", "经验", "教育", "标记", "主", "自由", "传统", "源", "革命", "蜡烛", "人口", "宠物"])
            sampleVoca4.setMeanList(means: ["文化", "経験", "教育", "象徴", "主人", "自由", "伝統", "ソース", "革命", "キャンドル", "人口", "ペット"])
            sampleVoca.append(sampleVoca4)
            
            
            // Spanish (Spain)
            let sampleVoca5: Voca = Voca()
            sampleVoca5.setTitle(title: "スペイン単語帳")
            sampleVoca5.setNum(num: -1)
            sampleVoca5.setCreateDate(uploadDate: date)
            sampleVoca5.setLanguage(language: "Spanish (Spain)")
            sampleVoca5.setE_Status(e_Status: 0)
            sampleVoca5.setE_Date(e_Date: date)
            sampleVoca5.setTag(tag: 5)
            sampleVoca5.setLearningCount(learningCount: 0)
            sampleVoca5.setLearningTime(learningTime: 0)
            sampleVoca5.setWordCount(wordCount: 12)
            sampleVoca5.setWordList(words: ["La cultura", "Experiencia", "Educacion", "Símbolo", "Maestro", "La libertad", "La tradicion", "Fuente", "Revolución", "Las velas", "Poblacion", "Las mascotas"])
            sampleVoca5.setMeanList(means: ["文化", "経験", "教育", "象徴", "主人", "自由", "伝統", "ソース", "革命", "キャンドル", "人口", "ペット"])
            sampleVoca.append(sampleVoca5)
            break
        default:
            // Arabic (Saudi Arabia)
            let sampleVoca1: Voca = Voca()
            sampleVoca1.setTitle(title: "Arabic voca")
            sampleVoca1.setNum(num: -5)
            sampleVoca1.setCreateDate(uploadDate: date)
            sampleVoca1.setLanguage(language: "Arabic (Saudi Arabia)")
            sampleVoca1.setE_Status(e_Status: 0)
            sampleVoca1.setE_Date(e_Date: date)
            sampleVoca1.setTag(tag: 1)
            sampleVoca1.setLearningCount(learningCount: 0)
            sampleVoca1.setLearningTime(learningTime: 0)
            sampleVoca1.setWordCount(wordCount: 12)
            sampleVoca1.setWordList(words: ["ثقافة", "تجربة", "التعليم", "كلمة", "مضيف", "حرية", "تقليد", "مصدر", "ثورة", "شمعة", "سكان", "الحيوانات الأليفة"])
            sampleVoca1.setMeanList(means: ["culture", "experience", "education", "symbol", "master", "liberty", "tradition", "source", "revolution", "candle", "population", "pet"])
            sampleVoca.append(sampleVoca1)

            // Japanese (Japan)
            let sampleVoca2: Voca = Voca()
            sampleVoca2.setTitle(title: "Japanese voca")
            sampleVoca2.setNum(num: -4)
            sampleVoca2.setCreateDate(uploadDate: date)
            sampleVoca2.setLanguage(language: "Japanese (Japan)")
            sampleVoca2.setE_Status(e_Status: 0)
            sampleVoca2.setE_Date(e_Date: date)
            sampleVoca2.setTag(tag: 2)
            sampleVoca2.setLearningCount(learningCount: 0)
            sampleVoca2.setLearningTime(learningTime: 0)
            sampleVoca2.setWordCount(wordCount: 12)
            sampleVoca2.setWordList(words: ["文化", "経験", "教育", "象徴", "主人", "自由", "伝統", "ソース", "革命", "キャンドル", "人口", "ペット"])
            sampleVoca2.setMeanList(means: ["culture", "experience", "education", "symbol", "master", "liberty", "tradition", "source", "revolution", "candle", "population", "pet"])
            sampleVoca.append(sampleVoca2)
            
            // Hindi (India)
            let sampleVoca3: Voca = Voca()
            sampleVoca3.setTitle(title: "Hindi voca")
            sampleVoca3.setNum(num: -3)
            sampleVoca3.setCreateDate(uploadDate: date)
            sampleVoca3.setLanguage(language: "Hindi (India)")
            sampleVoca3.setE_Status(e_Status: 0)
            sampleVoca3.setE_Date(e_Date: date)
            sampleVoca3.setTag(tag: 3)
            sampleVoca3.setLearningCount(learningCount: 0)
            sampleVoca3.setLearningTime(learningTime: 0)
            sampleVoca3.setWordCount(wordCount: 12)
            sampleVoca3.setWordList(words: ["संस्कृति", "अनुभव", "शिक्षा", "मार्क", "मेज़बान", "स्वतंत्रता", "परंपरा", "स्रोत", "क्रांति", "मोमबत्ती", "आबादी", "पालतू जानवर"])
            sampleVoca3.setMeanList(means: ["culture", "experience", "education", "symbol", "master", "liberty", "tradition", "source", "revolution", "candle", "population", "pet"])
            sampleVoca.append(sampleVoca3)
            
            // Chinese (China)
            let sampleVoca4: Voca = Voca()
            sampleVoca4.setTitle(title: "Chinese voca")
            sampleVoca4.setNum(num: -2)
            sampleVoca4.setCreateDate(uploadDate: date)
            sampleVoca4.setLanguage(language: "Chinese (China)")
            sampleVoca4.setE_Status(e_Status: 0)
            sampleVoca4.setE_Date(e_Date: date)
            sampleVoca4.setTag(tag: 4)
            sampleVoca4.setLearningCount(learningCount: 0)
            sampleVoca4.setLearningTime(learningTime: 0)
            sampleVoca4.setWordCount(wordCount: 12)
            sampleVoca4.setWordList(words: ["文化", "经验", "教育", "标记", "主", "自由", "传统", "源", "革命", "蜡烛", "人口", "宠物"])
            sampleVoca4.setMeanList(means: ["culture", "experience", "education", "symbol", "master", "liberty", "tradition", "source", "revolution", "candle", "population", "pet"])
            sampleVoca.append(sampleVoca4)
            
            // Spanish (Spain)
            let sampleVoca5: Voca = Voca()
            sampleVoca5.setTitle(title: "Spanish voca")
            sampleVoca5.setNum(num: -1)
            sampleVoca5.setCreateDate(uploadDate: date)
            sampleVoca5.setLanguage(language: "Spanish (Spain)")
            sampleVoca5.setE_Status(e_Status: 0)
            sampleVoca5.setE_Date(e_Date: date)
            sampleVoca5.setTag(tag: 5)
            sampleVoca5.setLearningCount(learningCount: 0)
            sampleVoca5.setLearningTime(learningTime: 0)
            sampleVoca5.setWordCount(wordCount: 12)
            sampleVoca5.setWordList(words: ["La cultura", "Experiencia", "Educacion", "Símbolo", "Maestro", "La libertad", "La tradicion", "Fuente", "Revolución", "Las velas", "Poblacion", "Las mascotas"])
            sampleVoca5.setMeanList(means: ["culture", "experience", "education", "symbol", "master", "liberty", "tradition", "source", "revolution", "candle", "population", "pet"])
            sampleVoca.append(sampleVoca5)
            break
        }

        return sampleVoca
    }
}


//        var i = 100
//        for lang in TTSData().languages {
//            let sampleVoca6: Voca = Voca()
//            sampleVoca6.setTitle(title: "test")
//            sampleVoca6.setNum(num: i)
//            sampleVoca6.setCreateDate(uploadDate: date)
//            sampleVoca6.setLanguage(language: lang)
//            sampleVoca6.setE_Status(e_Status: 0)
//            sampleVoca6.setE_Date(e_Date: date)
//            sampleVoca6.setTag(tag: 1)
//            sampleVoca6.setLearningCount(learningCount: 0)
//            sampleVoca6.setLearningTime(learningTime: 0)
//            sampleVoca6.setWordCount(wordCount: 4)
//            sampleVoca6.setWordList(words: ["1", "2", "3", "4"])
//            sampleVoca6.setMeanList(means: ["1", "2", "3", "4"])
//            sampleVoca.append(sampleVoca6)
//            i += 1
//        }
